.pragma library

const PRIVATE_MESSAGE_TEXT = 0
const PRIVATE_MESSAGE_STICKER = 1
const PRIVATE_MESSAGE_VOICE_NOTE = 2
const PRIVATE_MESSAGE_TYPE_BINARY_FILE = 3

const COURIER_MODE_IDLE = "#idle"
const COURIER_MODE_SERVER = "#server"
const COURIER_MODE_CLIENT = "#client"
const COURIER_MODE_SETTING_SERVER = "#sserver"
